name: Tic Tac Toe
description: A simple implementation of Tic Tac Toe game using Flutter framework.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
